default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: importmaps_development

test:
  <<: *default
  database: myapp_test
  database: importmaps_test

production:
  <<: *default
  database: importmaps_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
